import { Button, Descriptions, Modal, Space, Table, Tag, Typography, message } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { DashboardApi } from '../services/dashboardApi';
import type { DashboardDetail, DashboardVersion } from '../types';

export default function DashboardVersionsPage({ accessToken, dashboardId, navigate }: { accessToken: string; dashboardId: string; navigate: (path: string) => void }) {
  const api = useMemo(() => new DashboardApi(accessToken), [accessToken]); const [detail,setDetail]=useState<DashboardDetail>(); const [versions,setVersions]=useState<DashboardVersion[]>([]); const [selected,setSelected]=useState<DashboardVersion>(); const [toast,context]=message.useMessage();
  useEffect(() => { void Promise.all([api.detail(dashboardId),api.versions(dashboardId)]).then(([item,values])=>{setDetail(item);setVersions(values);}).catch((error:Error)=>void toast.error(error.message)); },[api,dashboardId,toast]);
  const restore = async (version: DashboardVersion) => { await api.createDraftFromVersion(dashboardId,version.id); void toast.success(`已从 v${version.version} 创建新草稿，线上版本未改变`); navigate(`/apps/dashboards/${dashboardId}/edit`); };
  return <div className="dashboard-versions-page">{context}<div className="page-heading"><div><Typography.Title level={3}>{detail?.summary.name ?? '看板'} · 版本</Typography.Title><Typography.Text type="secondary">发布版本不可变；恢复必须创建并发布新版本</Typography.Text></div><Button onClick={()=>navigate(`/apps/dashboards/${dashboardId}/view`)}>返回查看</Button></div><Table dataSource={versions} rowKey="id" columns={[{title:'版本',dataIndex:'version',render:(value:number)=><Tag color="blue">v{value}</Tag>},{title:'发布者',dataIndex:'publishedByName'},{title:'时间',dataIndex:'publishedAt',render:(value:string)=>new Date(value).toLocaleString()},{title:'说明',dataIndex:'releaseNotes'},{title:'本体 revision',dataIndex:'ontologyRevision'},{title:'页面 / 组件',render:(_:unknown,item:DashboardVersion)=>`${item.definition.pages.length} / ${item.definition.widgets.length}`},{title:'计划 hash',dataIndex:'queryPlanHash',render:(value:string)=><Typography.Text code>{value.slice(0,12)}…</Typography.Text>},{title:'健康',dataIndex:'healthStatus',render:(value:string)=><Tag color={value==='HEALTHY'?'green':'gold'}>{value}</Tag>},{title:'',render:(_:unknown,item:DashboardVersion)=><Space><Button onClick={()=>navigate(`/apps/dashboards/${dashboardId}/versions/${item.id}`)}>预览</Button><Button disabled={Boolean(detail?.activeDraft)} onClick={()=>void restore(item)}>从此版本创建草稿</Button><Button onClick={()=>setSelected(item)}>详情</Button></Space>}]}/><Modal footer={null} onCancel={()=>setSelected(undefined)} open={Boolean(selected)} title={`v${selected?.version} 发布证据`}><Descriptions column={1} items={[{key:'hash',label:'Query Plan hash',children:selected?.queryPlanHash},{key:'revision',label:'Ontology revision',children:selected?.ontologyRevision},{key:'schema',label:'Schema version',children:selected?.schemaVersion},{key:'note',label:'发布说明',children:selected?.releaseNotes||'—'}]} /></Modal></div>;
}
