blob.server.port: 6124
jobmanager.bind-host: 0.0.0.0
jobmanager.memory.process.size: 1024m
jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
metrics.reporter.prom.port: 9249
parallelism.default: 2
rest.address: 0.0.0.0
rest.bind-address: 0.0.0.0
state.checkpoints.dir: s3://flink-checkpoints/checkpoints
state.savepoints.dir: s3://flink-checkpoints/savepoints
s3.endpoint: http://minio:9000
s3.path.style.access: true
taskmanager.bind-host: 0.0.0.0
taskmanager.host: flink-taskmanager
taskmanager.memory.process.size: 1024m
taskmanager.numberOfTaskSlots: 2
