openapi: 3.1.0
info:
  title: Ontology OpenAPI
  description: Ontology OpenAPI Specification
  version: 0.0.1
servers:
  - url: http://localhost:4242
    description: Local development server
tags:
  - name: Ontology
  - name: DataSet
  - name: ObjectType
paths:
  "/v1/ontologies":
    get:
      tags:
        - Ontology
      summary: List Ontologies
      operationId: listOntologies
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
      responses:
        "200":
          description: Visible Ontologies
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OntologyPage"
    post:
      tags:
        - Ontology
      summary: Create an Ontology
      operationId: createOntology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateOntologyReq"
      responses:
        "201":
          description: Created Ontology
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Ontology"
  "/v1/ontologies/{ontologyId}":
    get:
      tags:
        - Ontology
      summary: Get an Ontology
      operationId: getOntology
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        "200":
          description: Ontology
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Ontology"
    patch:
      tags:
        - Ontology
      summary: Update an Ontology
      operationId: updateOntology
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateOntologyReq"
      responses:
        "200":
          description: Updated Ontology
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Ontology"
    delete:
      tags:
        - Ontology
      summary: Delete an Ontology
      operationId: deleteOntology
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        "204":
          description: Deleted Ontology
  /v1/ontologies/{ontologyId}/datasets:
    get:
      tags:
        - DataSet
      summary: List DataSets
      operationId: listDataSets
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
      responses:
        '200':
          description: DataSets in the Ontology
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetPage'
    post:
      tags:
        - DataSet
      summary: Create a DataSet
      description: Creates a DataSet.
      operationId: createDataSet
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDataSetReq'
      responses:
        '201':
          description: Created DataSet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSet'
  /v1/ontologies/{ontologyId}/datasets/{datasetId}:
    get:
      tags:
        - DataSet
      summary: Get a DataSet
      operationId: getDataSet
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: datasetId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        '200':
          description: DataSet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSet'
    patch:
      tags:
        - DataSet
      summary: Update a DataSet
      description: Updates metadata for Pipeline DataSets. Replaces fields and rows for Manual DataSets.
      operationId: updateDataSet
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: datasetId
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDataSetReq'
      responses:
        '200':
          description: Updated DataSet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSet'
    delete:
      tags:
        - DataSet
      summary: Delete a DataSet
      operationId: deleteDataSet
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: datasetId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        '204':
          description: Deleted DataSet
  "/v1/ontologies/{ontologyId}/object-types":
    get:
      tags:
        - ObjectType
      summary: List Object Types
      operationId: listObjectTypes
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        "200":
          description: Object Types in the Ontology
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ObjectType"
    post:
      tags:
        - ObjectType
      summary: Create an Object Type
      operationId: createObjectType
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateObjectTypeReq"
      responses:
        "201":
          description: Created Object Type
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ObjectType"
  "/v1/ontologies/{ontologyId}/object-types/{objectTypeId}":
    get:
      tags:
        - ObjectType
      summary: Get an Object Type
      operationId: getObjectType
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: objectTypeId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        "200":
          description: Object Type
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ObjectType"
    patch:
      tags:
        - ObjectType
      summary: Update an Object Type
      operationId: updateObjectType
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: objectTypeId
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateObjectTypeReq"
      responses:
        "200":
          description: Updated Object Type
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ObjectType"
    delete:
      tags:
        - ObjectType
      summary: Delete an Object Type
      operationId: deleteObjectType
      parameters:
        - in: path
          name: ontologyId
          required: true
          schema:
            type: string
            maxLength: 32
        - in: path
          name: objectTypeId
          required: true
          schema:
            type: string
            maxLength: 32
      responses:
        "204":
          description: Deleted Object Type
components:
  schemas:
    CreateOntologyReq:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
    UpdateOntologyReq:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
    OntologyPage:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Ontology"
        total:
          type: integer
          format: int64
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
    Ontology:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateDataSetReq:
      type: object
      additionalProperties: false
      required:
        - id
        - name
      properties:
        id:
          type: string
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
        fields:
          type: array
          maxItems: 32
          items:
            $ref: '#/components/schemas/DataSetField'
    UpdateDataSetReq:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        id:
          type: string
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
        fields:
          type: array
          maxItems: 32
          items:
            $ref: '#/components/schemas/DataSetField'
    DataSetPage:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DataSet'
        total:
          type: integer
          format: int64
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
    DataSet:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/DataSetField'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    DataSetField:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 32
        type:
          type: string
          enum:
            - BOOLEAN
            - DATE
            - DATETIME
            - DECIMAL
            - INTEGER
            - JSON
            - TEXT
        nullable:
          type: boolean
    CreateObjectTypeReq:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
    UpdateObjectTypeReq:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 32
        description:
          type: string
          maxLength: 1024
    ObjectType:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        ontologyId:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
