spring:
  application:
    name: ontology

server:
  port: 4242

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
