/* eslint-disable react-hooks/exhaustive-deps */
import { ArrowLeftOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Checkbox, Col, Form, Input, InputNumber, Radio, Row, Select, Steps, Switch, Table, Tag, Typography, message } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { modelingApi } from './ontology.service';
import type { OntologyResource, PropertyDraft, ResourceKind } from './ontology.types';
import { resourcePath } from './OntologyOverviewPage';

const { Text, Title } = Typography;
const kindTitle: Record<ResourceKind, string> = { OBJECT_TYPE: '对象类型', LINK_TYPE: '关系类型', INTERFACE: 'Interface', ACTION: 'Action', FUNCTION: 'Function' };

export default function ResourceEditorPage({ accessToken, displayName, kind, navigate, userId }: { accessToken: string; displayName: string; kind: ResourceKind; navigate: (path: string) => void; userId: string }) {
  if (kind === 'OBJECT_TYPE') return <ObjectTypeWizard accessToken={accessToken} displayName={displayName} navigate={navigate} userId={userId} />;
  return <GenericResourceEditor accessToken={accessToken} displayName={displayName} kind={kind} navigate={navigate} userId={userId} />;
}

function ObjectTypeWizard({ accessToken, displayName, navigate, userId }: { accessToken: string; displayName: string; navigate: (path: string) => void; userId: string }) {
  const api = useMemo(() => modelingApi(accessToken), [accessToken]);
  const [current, setCurrent] = useState(0);
  const [saving, setSaving] = useState(false);
  const [sourceMode, setSourceMode] = useState('ACTION');
  const [form] = Form.useForm();
  const [properties, setProperties] = useState<PropertyDraft[]>([
    { apiName: 'id', displayName: '标识', valueType: 'STRING', required: true, primaryKey: true, titleProperty: false, searchable: true, filterable: true, sortable: true, sensitive: false },
    { apiName: 'name', displayName: '名称', valueType: 'STRING', required: true, primaryKey: false, titleProperty: true, searchable: true, filterable: true, sortable: true, sensitive: false },
  ]);
  async function save() {
    await form.validateFields(['displayName', 'apiName']);
    const values = form.getFieldsValue(true) as Record<string, string | boolean>; setSaving(true);
    try {
      const resource = await api.createResource('OBJECT_TYPE', { ...values, ownerId: userId, ownerName: displayName, sourceMode, tags: splitTags(typeof values.tags === 'string' ? values.tags : undefined), properties });
      message.success('对象类型草稿已保存；尚未部署'); navigate(resourcePath(resource.kind, resource.id));
    } catch (error) { message.error((error as Error).message); } finally { setSaving(false); }
  }
  const update = (index: number, value: Partial<PropertyDraft>) => setProperties((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...value } : item));
  return <div className="ontology-editor-page"><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/ontology/object-types')} type="text">返回对象类型</Button><div className="ontology-editor-heading"><Title level={2}>新建对象类型</Title><Tag color="blue">只保存草稿</Tag></div><Steps current={current} items={[{ title: '创建方式' }, { title: '基本信息' }, { title: '属性与标识' }, { title: '检查并保存' }]} />
    <Form form={form} layout="vertical" initialValues={{ maturity: 'EXPERIMENTAL', promoted: false }}>
      <Card className="ontology-wizard-card">{current === 0 && <><Title level={4}>选择规范数据来源</Title><Radio.Group className="source-mode-cards" onChange={(event) => setSourceMode(event.target.value)} value={sourceMode}><Radio.Button value="PIPELINE"><strong>从 Pipeline 输出创建</strong><span>推荐：Schema 与字段血缘来自一个主 Sink</span></Radio.Button><Radio.Button value="ACTION"><strong>创建空对象类型</strong><span>由 Action mutation 通道管理数据</span></Radio.Button></Radio.Group><Alert message="连接、表和文件不能绕过 Pipeline 直接成为正式对象映射。" showIcon type="info" /></>}
      {current === 1 && <Row gutter={18}><Col span={12}><Form.Item label="显示名称" name="displayName" rules={[{ required: true }]}><Input placeholder="例如：客户" /></Form.Item></Col><Col span={12}><Form.Item label="API 名称" name="apiName" rules={[{ required: true, pattern: /^[A-Za-z][A-Za-z0-9_]*$/ }]}><Input placeholder="Customer" /></Form.Item></Col><Col span={24}><Form.Item label="描述" name="description"><Input.TextArea rows={3} /></Form.Item></Col><Col span={8}><Form.Item label="成熟度" name="maturity"><Select options={['EXPERIMENTAL', 'ACTIVE', 'DEPRECATED'].map((value) => ({ value }))} /></Form.Item></Col><Col span={8}><Form.Item label="标签" name="tags"><Input placeholder="crm, core" /></Form.Item></Col><Col span={8}><Form.Item label="核心对象" name="promoted" valuePropName="checked"><Switch /></Form.Item></Col></Row>}
      {current === 2 && <><div className="tab-toolbar"><div><Title level={4}>属性与标识</Title><Text type="secondary">主键仅允许 string / integer / long；敏感属性默认不索引。</Text></div><Button icon={<PlusOutlined />} onClick={() => setProperties((items) => [...items, { apiName: '', displayName: '', valueType: 'STRING', required: false, primaryKey: false, titleProperty: false, searchable: true, filterable: true, sortable: false, sensitive: false }])}>添加属性</Button></div><Table dataSource={properties} pagination={false} rowKey={(_, index) => String(index)} size="small" columns={[{ title: '显示名称', render: (_, row, index) => <Input onChange={(event) => update(index, { displayName: event.target.value })} value={row.displayName} /> }, { title: 'API 名称', render: (_, row, index) => <Input onChange={(event) => update(index, { apiName: event.target.value })} value={row.apiName} /> }, { title: '类型', render: (_, row, index) => <Select onChange={(value) => update(index, { valueType: value })} options={['STRING', 'INTEGER', 'LONG', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'ENUM', 'STRING_ARRAY', 'INTEGER_ARRAY', 'JSON'].map((value) => ({ value }))} value={row.valueType} /> }, { title: '必填', render: (_, row, index) => <Checkbox checked={row.required} onChange={(event) => update(index, { required: event.target.checked })} /> }, { title: '主键', render: (_, row, index) => <Checkbox checked={row.primaryKey} onChange={(event) => setProperties((items) => items.map((item, i) => ({ ...item, primaryKey: i === index && event.target.checked, required: i === index && event.target.checked ? true : item.required })))} /> }, { title: '标题', render: (_, row, index) => <Checkbox checked={row.titleProperty} onChange={(event) => setProperties((items) => items.map((item, i) => ({ ...item, titleProperty: i === index && event.target.checked })))} /> }, { title: '敏感', render: (_, row, index) => <Checkbox checked={row.sensitive} onChange={(event) => update(index, { sensitive: event.target.checked, searchable: event.target.checked ? false : row.searchable })} /> }, { title: '', render: (_, __, index) => <Button aria-label="删除属性" danger icon={<DeleteOutlined />} onClick={() => setProperties((items) => items.filter((_, i) => i !== index))} type="text" /> }]} /></>}
      {current === 3 && <div className="ontology-review"><Alert message="检查通过后只生成草稿，不部署 HugeGraph 或 OpenSearch。" showIcon type="success" /><DescriptionsReview form={form} sourceMode={sourceMode} properties={properties} /></div>}</Card>
    </Form><div className="ontology-wizard-actions"><Button disabled={current === 0} onClick={() => setCurrent((value) => value - 1)}>上一步</Button>{current < 3 ? <Button onClick={async () => { if (current === 1) await form.validateFields(['displayName', 'apiName']); setCurrent((value) => value + 1); }} type="primary">下一步</Button> : <Button loading={saving} onClick={() => void save()} type="primary">保存草稿</Button>}</div>
  </div>;
}

function DescriptionsReview({ form, properties, sourceMode }: { form: ReturnType<typeof Form.useForm>[0]; properties: PropertyDraft[]; sourceMode: string }) {
  const values = form.getFieldsValue(true) as Record<string, string>; const primary = properties.find((property) => property.primaryKey); const title = properties.find((property) => property.titleProperty) ?? primary;
  return <div className="review-grid"><div><Text type="secondary">显示 / API 名称</Text><strong>{values.displayName || '—'} / {values.apiName || '—'}</strong></div><div><Text type="secondary">来源</Text><strong>{sourceMode}</strong></div><div><Text type="secondary">主键 / 标题</Text><strong>{primary?.apiName || '缺失'} / {title?.apiName || '缺失'}</strong></div><div><Text type="secondary">属性</Text><strong>{properties.length} 个 · {properties.filter((property) => property.sensitive).length} 个敏感</strong></div></div>;
}

function GenericResourceEditor({ accessToken, displayName, kind, navigate, userId }: { accessToken: string; displayName: string; kind: ResourceKind; navigate: (path: string) => void; userId: string }) {
  const api = useMemo(() => modelingApi(accessToken), [accessToken]); const [form] = Form.useForm(); const [objects, setObjects] = useState<OntologyResource[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { void api.listResources('OBJECT_TYPE').then(setObjects); }, []);
  async function save() { const values = await form.validateFields(); setSaving(true); try { const target = values.targetObjectTypeId || values.leftObjectTypeId; const targetObject = objects.find((item) => item.id === target); const firstProperty = targetObject?.properties[0]; const body: Record<string, unknown> = { ...values, ownerId: userId, ownerName: displayName, maturity: 'EXPERIMENTAL', tags: splitTags(values.tags) };
      if (kind === 'LINK_TYPE') Object.assign(body, { sourceMode: 'FOREIGN_KEY', leftDisplayName: values.displayName, rightDisplayName: `反向${values.displayName}` });
      if (kind === 'INTERFACE') Object.assign(body, { slots: [{ apiName: 'name', displayName: '名称', valueType: 'STRING', required: true }], implementations: firstProperty ? [{ objectTypeId: target, slotApiName: 'name', propertyId: firstProperty.id }] : [] });
      if (kind === 'ACTION') Object.assign(body, { operation: values.operation, approvalPolicy: values.approvalPolicy, parameters: [{ apiName: 'value', displayName: '新值', valueType: 'STRING', required: true, sensitive: false }], rules: firstProperty ? [{ type: 'SET_PROPERTY', targetPropertyId: firstProperty.id, valueFrom: 'value' }] : [], submitCondition: {} });
      if (kind === 'FUNCTION') Object.assign(body, { outputType: values.outputType, queryDsl: { fromObjectTypeId: target, operation: 'FILTER', limit: 100 }, dependencyIds: target ? [target] : [], timeoutMs: values.timeoutMs, maxResults: 1000, cacheSeconds: 60, parameters: [] });
      const resource = await api.createResource(kind, body); message.success(`${kindTitle[kind]}草稿已保存`); navigate(resourcePath(resource.kind, resource.id));
    } catch (error) { message.error((error as Error).message); } finally { setSaving(false); } }
  const objectOptions = objects.map((item) => ({ label: `${item.displayName} (${item.apiName})`, value: item.id }));
  return <div className="ontology-editor-page"><Button icon={<ArrowLeftOutlined />} onClick={() => navigate(`/ontology/${resourcePath(kind, '').split('/')[2]}`)} type="text">返回{kindTitle[kind]}</Button><div className="ontology-editor-heading"><Title level={2}>新建{kindTitle[kind]}</Title><Tag color="blue">独立草稿页</Tag></div><Card><Form form={form} layout="vertical" initialValues={{ cardinality: 'N:1', operation: 'UPDATE', approvalPolicy: 'ALWAYS', outputType: 'TABLE', timeoutMs: 5000 }}><Row gutter={18}><Col span={12}><Form.Item label="显示名称" name="displayName" rules={[{ required: true }]}><Input /></Form.Item></Col><Col span={12}><Form.Item label="API 名称" name="apiName" rules={[{ required: true, pattern: /^[A-Za-z][A-Za-z0-9_]*$/ }]}><Input /></Form.Item></Col><Col span={24}><Form.Item label="描述" name="description"><Input.TextArea rows={3} /></Form.Item></Col><Col span={12}><Form.Item label="标签" name="tags"><Input placeholder="domain, stable" /></Form.Item></Col>{kind === 'LINK_TYPE' && <><Col span={8}><Form.Item label="左端对象" name="leftObjectTypeId" rules={[{ required: true }]}><Select options={objectOptions} /></Form.Item></Col><Col span={8}><Form.Item label="右端对象" name="rightObjectTypeId" rules={[{ required: true }]}><Select options={objectOptions} /></Form.Item></Col><Col span={8}><Form.Item label="基数" name="cardinality"><Select options={['1:1', '1:N', 'N:1', 'N:M'].map((value) => ({ value }))} /></Form.Item></Col></>}{kind === 'INTERFACE' && <Col span={12}><Form.Item label="示例实现对象" name="leftObjectTypeId" rules={[{ required: true }]}><Select options={objectOptions} /></Form.Item></Col>}{kind === 'ACTION' && <><Col span={8}><Form.Item label="目标对象" name="targetObjectTypeId" rules={[{ required: true }]}><Select options={objectOptions} /></Form.Item></Col><Col span={8}><Form.Item label="操作类型" name="operation"><Select options={['CREATE', 'UPDATE', 'RETIRE', 'LINK', 'UNLINK'].map((value) => ({ value }))} /></Form.Item></Col><Col span={8}><Form.Item label="审批策略" name="approvalPolicy"><Select options={['NONE', 'ALWAYS', 'CONDITIONAL'].map((value) => ({ value }))} /></Form.Item></Col></>}{kind === 'FUNCTION' && <><Col span={8}><Form.Item label="声明依赖对象" name="targetObjectTypeId" rules={[{ required: true }]}><Select options={objectOptions} /></Form.Item></Col><Col span={8}><Form.Item label="输出类型" name="outputType"><Select options={['SCALAR', 'OBJECT_SET', 'TABLE', 'BOOLEAN'].map((value) => ({ value }))} /></Form.Item></Col><Col span={8}><Form.Item label="超时 (ms)" name="timeoutMs"><InputNumber max={30000} min={100} style={{ width: '100%' }} /></Form.Item></Col></>}</Row><div className="edit-actions"><Button onClick={() => navigate(`/ontology/${resourcePath(kind, '').split('/')[2]}`)}>取消</Button><Button loading={saving} onClick={() => void save()} type="primary">保存草稿</Button></div></Form></Card></div>;
}

function splitTags(value?: string) { return value?.split(',').map((tag) => tag.trim()).filter(Boolean) ?? []; }
