import { ArrowLeftOutlined, CopyOutlined, ExperimentOutlined, FunctionOutlined, RobotOutlined, StarOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Descriptions, Empty, List, Modal, Skeleton, Space, Tabs, Tag, Timeline, Typography, message } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { ExplorerApi } from './explorer.service';
import type { CapabilityResponse, ObjectDetail } from './explorer.types';
import { activeOntologyId } from '../ontologyContext';

export default function ObjectDetailPage({ accessToken, canBuild, navigate, objectId, objectTypeId }: { accessToken: string; canBuild: boolean; navigate: (path: string) => void; objectId: string; objectTypeId: string }) {
  const api = useMemo(() => new ExplorerApi(accessToken), [accessToken]); const [notice, holder] = message.useMessage(); const [detail, setDetail] = useState<ObjectDetail>(); const [links, setLinks] = useState<Array<Record<string, unknown>>>([]); const [capabilities, setCapabilities] = useState<CapabilityResponse>(); const [activity, setActivity] = useState<Array<Record<string, unknown>>>([]); const [provenance, setProvenance] = useState<Record<string, unknown>>(); const [error, setError] = useState('');
  useEffect(() => { void Promise.all([api.object(objectTypeId, objectId), api.links(objectTypeId, objectId), api.capabilities(objectTypeId, objectId), api.activity(objectTypeId, objectId), api.provenance(objectTypeId, objectId)]).then(([object, relationPage, capability, events, source]) => { setDetail(object); setLinks(relationPage.items); setCapabilities(capability); setActivity(events); setProvenance(source); }).catch((cause: Error) => setError(cause.message)); }, [api, objectId, objectTypeId]);
  const actionPreview = async (id: string, name: string) => { try { const workspaceId = activeOntologyId(); const response = await fetch(`/api/ontology/v1/modeling/actions/${id}/preview`, { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json', 'X-Ontology-Id': workspaceId, 'X-Workspace-Id': workspaceId }, body: JSON.stringify({ objectId, objectVersion: detail?.version, parameters: {} }) }); const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(body.detail ?? 'Preview 失败')); Modal.info({ title: `${name} · Preview → Diff`, width: 720, content: <pre>{JSON.stringify(body, null, 2)}</pre> }); } catch (cause) { notice.error(cause instanceof Error ? cause.message : 'Preview 失败'); } };
  if (error) return <Alert message={error} showIcon type="error" />; if (!detail) return <Skeleton active />;
  const visible = detail.objectType.properties.filter((item) => !item.sensitive);
  return <div className="object-detail-page">{holder}<Button icon={<ArrowLeftOutlined />} onClick={() => navigate(`/ontology/explorer/${objectTypeId}`)} type="text">返回探索</Button><div className="object-detail-header"><div><Space><Typography.Title level={2}>{detail.title}</Typography.Title><Tag>{detail.objectType.displayName}</Tag><Tag color="success">质量通过</Tag></Space><Space><Typography.Text code>{detail.objectId}</Typography.Text><Typography.Text>v{detail.version}</Typography.Text><Typography.Text>{detail.etag}</Typography.Text><Typography.Text type="secondary">更新 {new Date(detail.updatedAt).toLocaleString()}</Typography.Text></Space></div><Space wrap><Button icon={<StarOutlined />}>收藏</Button><Button icon={<CopyOutlined />} onClick={() => void navigator.clipboard.writeText(window.location.href)}>复制链接</Button>{capabilities?.actions.slice(0, 1).map((action) => <Button disabled={!canBuild} key={action.id} onClick={() => void actionPreview(action.id, action.displayName)} type="primary">{action.displayName}</Button>)}<Button icon={<RobotOutlined />}>AIP</Button></Space></div><Tabs items={[
    { key: 'overview', label: '概览', children: <div className="detail-grid"><Card title="突出属性"><Descriptions bordered column={1} items={visible.slice(0, 6).map((property) => ({ key: property.id, label: property.displayName, children: value(detail.properties[property.apiName]) }))} /></Card><Card title="标准对象视图"><p>自动生成的 Full View，Panel View 可在探索右侧打开并保留查询。</p><Tag color="blue">ontology revision {detail.ontologyRevision}</Tag>{detail.redactedFields.length > 0 && <Alert message={`${detail.redactedFields.length} 个字段已由服务端字段策略隐藏`} type="info" />}</Card></div> },
    { key: 'properties', label: '全部属性', children: <Descriptions bordered column={1} items={visible.map((property) => ({ key: property.id, label: <span>{property.displayName} <Typography.Text code>{property.apiName}</Typography.Text></span>, children: <Space>{value(detail.properties[property.apiName])}<Tag>{property.valueType}</Tag><Typography.Text type="secondary">来源 payload.{property.apiName}</Typography.Text></Space> }))} /> },
    { key: 'relations', label: `关系 (${links.length})`, children: links.length ? <List dataSource={links} renderItem={(item) => <List.Item actions={[<Button key="open" onClick={() => navigate(`/ontology/explorer/${String(item.targetObjectTypeId)}/${encodeURIComponent(String(item.targetObjectId))}`)} type="link">沿关系打开</Button>]}><List.Item.Meta title={String(item.targetTitle)} description={`${String(item.direction)} · ${String(item.linkTypeName)} · ${String(item.targetObjectId)}`} /></List.Item>} /> : <Empty description="暂无有权关系" /> },
    { key: 'actions', label: 'Action', children: <List dataSource={capabilities?.actions} locale={{ emptyText: '当前角色没有可执行 Action' }} renderItem={(action) => <List.Item actions={[<Button disabled={!canBuild} icon={<ExperimentOutlined />} key="preview" onClick={() => void actionPreview(action.id, action.displayName)}>Preview → Diff</Button>]}><List.Item.Meta title={action.displayName} description={`${action.apiName} · v${action.version} · 必须 Preview 后执行`} /></List.Item>} /> },
    { key: 'functions', label: 'Function', children: <List dataSource={capabilities?.functions} renderItem={(fn) => <List.Item actions={[<Button icon={<FunctionOutlined />} key="run">运行只读 Function</Button>]}><List.Item.Meta title={fn.displayName} description={`${fn.apiName} · 精确 v${fn.version} · 调用者权限`} /></List.Item>} /> },
    { key: 'activity', label: '活动', children: activity.length ? <Timeline items={activity.map((item) => ({ color: item.status === 'PROJECTED' ? 'green' : 'blue', children: <><strong>{String(item.kind)} · {String(item.status)}</strong><p>{String(item.summary)} · {String(item.correlationId)}</p></> }))} /> : <Empty description="暂无活动" /> },
    { key: 'provenance', label: '数据来源与血缘', children: <Card><pre>{JSON.stringify(provenance, null, 2)}</pre></Card> },
  ]} /></div>;
}

function value(input: unknown) { if (input == null) return <Typography.Text type="secondary">未设置</Typography.Text>; return typeof input === 'object' ? <code>{JSON.stringify(input)}</code> : String(input); }
